config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  root 'main#home'
  get 'signup' => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users
  resources :tasks
  resources :tasks do
    member do
        get :complete
    end
end
  

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 750 }
  
  PRIORITIES = ['Low', 'Medium', 'High']
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :tasks, dependent: :destroy
    attr_accessor :remember_token
    before_save { self.email = email.downcase }
    validates :name,  presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i 
    validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness:  { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
    
    # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def home
    @task = current_user.tasks.build if logged_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # Log the user in and redirect to the user's show page.
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_back_or user
    else
      # Create an error message.
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :logged_in_user, only: [:create, :index, :destroy]
    before_action :admin_user, only: [:destroy]
    

  def create
    @task = current_user.tasks.build(task_params)
    if @task.save
      flash[:success] = "Task created!"
      redirect_to root_url
    else
      render 'main/home'
    end
  end
  
    def index
        @tasks = Task.paginate(page: params[:page])
    end

  def destroy
    Task.find(params[:id]).destroy
    flash[:success] = "Micropost deleted"
    redirect_to :back
  end
  
  def complete
    task = Task.find(params[:id])
    task.is_complete = true 
    task.save
    flash[:success] = "Task marked complete"
    redirect_to :back
  end
  
  def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

  private

    def task_params
      params.require(:task).permit(:content, :priority, :is_complete)
    end
    
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :index, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy
  
  def index
    @users = User.paginate(page: params[:page])
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Task Management App!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end
  
  def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
    
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end
  
  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
    
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def full_title(page_title = '')
        base_title = "Task Management App"
        if page_title.empty?
            base_title
        else
            page_title + " | " + base_title
        end
    end
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
   # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end
  
  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end


  # Returns the user corresponding to the remember token cookie.
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end
  
  # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
  
  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end
  
  # Logs out the current user.
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
  
  def current_user?(user)
    user == current_user
  end
  
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  def store_location
    session[:forwarding_url] = request.url if request.get?
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Task Management
  </small>
  <nav id="footer-nav">
    <ul>
      <li><%= link_to "Home",   root_path %></li>
      <% if !logged_in? %>
        <li><%= link_to "Log in", login_path %></li>
      <% else %>
        <li><%= link_to "Users", users_path %></li>
        <li><%= link_to "Tasks", tasks_path %></li>
      <% end %>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "task management", root_path, id: "logo" %>
    <nav id="header-nav">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li><%= link_to "Tasks", tasks_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/main/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="task_form">
        <%= render 'shared/task_form' %>
      </section>
    </aside>
  </div>
<% else %>

  <div class="center jumbotron">
    <h1>Welcome to the Task Management App</h1>

    <h2>
      This is an app for a MGMT3000 project.
    </h2>

    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_task_form.html.erb
<%= form_for(@task) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new task..." %>
    <%= f.label :priority %>:
    <%= f.select :priority, Task::PRIORITIES %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.tasks.count, "task") %></span>

app/views/tasks/_task.html.erb
<li id="task-<%= task.id %>">
    <% if task.is_complete != true %>
        <% if task.priority.casecmp("low").zero? %>
            <div class="low-wrapper">
                <span class="user"><%= link_to task.user.name, task.user %> posted the following task:</span>
                <span class="content"><%= task.content %></span>
                <span class="priority">Priority: <%= task.priority %></span>
                <span class="timestamp">
                    Posted <%= time_ago_in_words(task.created_at) %> ago.
                </span>
                <div align="center"><%= link_to "Mark Complete", complete_task_path(task), data: {confirm: "Are you sure?"}, class: "btn btn-primary" %></div>
                <%= link_to "Delete this post", task, method: :delete,
                                       data: { confirm: "Are you sure?" } %>
            </div>
        <% elsif task.priority.casecmp("medium").zero? %>
            <div class="medium-wrapper">
                <span class="user"><%= link_to task.user.name, task.user %> posted the following task:</span>
                <span class="content"><%= task.content %></span>
                <span class="priority">Priority: <%= task.priority %></span>
                <span class="timestamp">
                    Posted <%= time_ago_in_words(task.created_at) %> ago.
                </span>
                <div align="center"><%= link_to "Mark Complete", complete_task_path(task), data: {confirm: "Are you sure?"}, class: "btn btn-primary" %></div>
                <%= link_to "Delete this post", task, method: :delete,
                                       data: { confirm: "Are you sure?" } %>
            </div>
        <% elsif task.priority.casecmp("high").zero? %>
            <div class="high-wrapper">
                <span class="user"><%= link_to task.user.name, task.user %> posted the following task:</span>
                <span class="content"><%= task.content %></span>
                <span class="priority">Priority: <%= task.priority %></span>
                <span class="timestamp">
                    Posted <%= time_ago_in_words(task.created_at) %> ago.
                </span>
                <div align="center"><%= link_to "Mark Complete", complete_task_path(task), data: {confirm: "Are you sure?"}, class: "btn btn-primary" %></div>
                <%= link_to "Delete this post", task, method: :delete,
                                       data: { confirm: "Are you sure?" } %>
            </div>
        <% end %>
    <% else %>
        <div class="complete-wrapper">
            <span class="user"><%= link_to task.user.name, task.user %> posted the following task:</span>
            <span class="content"><%= task.content %></span>
            <span class="completed">Complete!</span>
            <span class="timestamp">
                Posted <%= time_ago_in_words(task.created_at) %> ago.
            </span>
            <span class="timestamp">
                 Completed <%= time_ago_in_words(task.updated_at) %> ago.
            </span>
            <%= link_to "Delete this post", task, method: :delete,
                                       data: { confirm: "Are you sure?" } %>
        </div>
    <% end %>
</li>

app/views/tasks/index.html.erb
<% provide(:title, 'All tasks') %>
<h1>All tasks</h1>

<%= will_paginate %>

<ul class="tasks">
  <%= render @tasks %>
</ul>

<%= will_paginate %>

app/views/tasks/new.html.erb
<div class="row">
    <aside class="col-md-4">
      <section class="task_form">
        <%= render 'shared/task_form' %>
      </section>
    </aside>
</div>

app/views/users/_user.html.erb
<li>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "Delete this user", user, method: :delete,
                                  data: { confirm: "Are you sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% if !logged_in? %>
  <h1>Sign up</h1>

  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>

        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>

        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>

        <%= f.submit "Create my account", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
<% else %>
  You are already logged in to an account!
<% end %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>